//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JsonParseApp.Models.DpacDb
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class DPACEntities : DbContext
    {
        public DPACEntities()
            : base("name=DPACEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<customer> customers { get; set; }
        public virtual DbSet<customers_financial> customers_financial { get; set; }
        public virtual DbSet<individual_financials> individual_financials { get; set; }
        public virtual DbSet<loan> loans { get; set; }
        public virtual DbSet<studentln> studentlns { get; set; }
        public virtual DbSet<studentln_borr> studentln_borr { get; set; }
        public virtual DbSet<fxrefbor> fxrefbors { get; set; }
    
        public virtual int FMS_InsertIntoFxrefbor(string fbonumber, string fxrbtype, Nullable<System.DateTime> fxrmoddt, string appnumber)
        {
            var fbonumberParameter = fbonumber != null ?
                new ObjectParameter("fbonumber", fbonumber) :
                new ObjectParameter("fbonumber", typeof(string));
    
            var fxrbtypeParameter = fxrbtype != null ?
                new ObjectParameter("fxrbtype", fxrbtype) :
                new ObjectParameter("fxrbtype", typeof(string));
    
            var fxrmoddtParameter = fxrmoddt.HasValue ?
                new ObjectParameter("fxrmoddt", fxrmoddt) :
                new ObjectParameter("fxrmoddt", typeof(System.DateTime));
    
            var appnumberParameter = appnumber != null ?
                new ObjectParameter("appnumber", appnumber) :
                new ObjectParameter("appnumber", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("FMS_InsertIntoFxrefbor", fbonumberParameter, fxrbtypeParameter, fxrmoddtParameter, appnumberParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> FMS_UpdateAppNumberNext(string appId)
        {
            var appIdParameter = appId != null ?
                new ObjectParameter("AppId", appId) :
                new ObjectParameter("AppId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("FMS_UpdateAppNumberNext", appIdParameter);
        }
    
        public virtual ObjectResult<GetIvorPixabajCustomerCode_Result> GetIvorPixabajCustomerCode(string cust)
        {
            var custParameter = cust != null ?
                new ObjectParameter("Cust", cust) :
                new ObjectParameter("Cust", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetIvorPixabajCustomerCode_Result>("GetIvorPixabajCustomerCode", custParameter);
        }
    
        public virtual ObjectResult<GetCustomerName_Result> GetCustomerName(string applicantId)
        {
            var applicantIdParameter = applicantId != null ?
                new ObjectParameter("applicantId", applicantId) :
                new ObjectParameter("applicantId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetCustomerName_Result>("GetCustomerName", applicantIdParameter);
        }
    
        public virtual int updateCustCode(string cust)
        {
            var custParameter = cust != null ?
                new ObjectParameter("Cust", cust) :
                new ObjectParameter("Cust", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("updateCustCode", custParameter);
        }
    }
}
