//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JsonParseApp.Models.DpacDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class fxrefbor
    {
        public string fbonumbr { get; set; }
        public string fxrbtype { get; set; }
        public string fxrmodid { get; set; }
        public Nullable<System.DateTime> fxrmoddt { get; set; }
        public int idnum { get; set; }
        public Nullable<bool> flarchive { get; set; }
        public string appnumber { get; set; }
    
        public virtual customer customer { get; set; }
        public virtual loan loan { get; set; }
    }
}
