//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JsonParseApp.Models.DpacDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class individual_financials
    {
        public int idnum { get; set; }
        public string fbonumbr { get; set; }
        public Nullable<decimal> amount { get; set; }
        public string description { get; set; }
        public string code { get; set; }
        public Nullable<bool> consolidate { get; set; }
    
        public virtual customer customer { get; set; }
    }
}
