//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JsonParseApp.Models.DpacDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class studentln
    {
        public string appnumber { get; set; }
        public string course { get; set; }
        public string school { get; set; }
        public Nullable<decimal> duration { get; set; }
        public Nullable<decimal> approxcost { get; set; }
        public string pastschool1 { get; set; }
        public string pastschool2 { get; set; }
        public string pastschool3 { get; set; }
        public string pastqual1 { get; set; }
        public string pastqual2 { get; set; }
        public string pastqual3 { get; set; }
        public string qual1 { get; set; }
        public string qual2 { get; set; }
        public string qual3 { get; set; }
        public Nullable<decimal> studlevel { get; set; }
        public string sub1 { get; set; }
        public string grade1 { get; set; }
        public string sub2 { get; set; }
        public string grade2 { get; set; }
        public string sub3 { get; set; }
        public string grade3 { get; set; }
        public string sub4 { get; set; }
        public string grade4 { get; set; }
        public string sub5 { get; set; }
        public string grade5 { get; set; }
        public string sub6 { get; set; }
        public string grade6 { get; set; }
        public string sub7 { get; set; }
        public string grade7 { get; set; }
        public string sub8 { get; set; }
        public string grade8 { get; set; }
        public string sub9 { get; set; }
        public string grade9 { get; set; }
        public string sub10 { get; set; }
        public string grade10 { get; set; }
        public string sub11 { get; set; }
        public string grade11 { get; set; }
        public string sub12 { get; set; }
        public string grade12 { get; set; }
        public string sub13 { get; set; }
        public string grade13 { get; set; }
        public string level { get; set; }
        public Nullable<System.DateTime> date_lact { get; set; }
        public string user_lact { get; set; }
        public Nullable<decimal> year1item1 { get; set; }
        public Nullable<decimal> year2item1 { get; set; }
        public Nullable<decimal> year3item1 { get; set; }
        public Nullable<decimal> year4item1 { get; set; }
        public Nullable<decimal> year5item1 { get; set; }
        public Nullable<decimal> year6item1 { get; set; }
        public Nullable<decimal> year7item1 { get; set; }
        public Nullable<decimal> year1item2 { get; set; }
        public Nullable<decimal> year2item2 { get; set; }
        public Nullable<decimal> year3item2 { get; set; }
        public Nullable<decimal> year4item2 { get; set; }
        public Nullable<decimal> year5item2 { get; set; }
        public Nullable<decimal> year6item2 { get; set; }
        public Nullable<decimal> year7item2 { get; set; }
        public Nullable<decimal> year1item3 { get; set; }
        public Nullable<decimal> year2item3 { get; set; }
        public Nullable<decimal> year3item3 { get; set; }
        public Nullable<decimal> year4item3 { get; set; }
        public Nullable<decimal> year5item3 { get; set; }
        public Nullable<decimal> year6item3 { get; set; }
        public Nullable<decimal> year7item3 { get; set; }
        public Nullable<decimal> year1item4 { get; set; }
        public Nullable<decimal> year2item4 { get; set; }
        public Nullable<decimal> year3item4 { get; set; }
        public Nullable<decimal> year4item4 { get; set; }
        public Nullable<decimal> year5item4 { get; set; }
        public Nullable<decimal> year6item4 { get; set; }
        public Nullable<decimal> year7item4 { get; set; }
        public Nullable<decimal> year1item5 { get; set; }
        public Nullable<decimal> year2item5 { get; set; }
        public Nullable<decimal> year3item5 { get; set; }
        public Nullable<decimal> year4item5 { get; set; }
        public Nullable<decimal> year5item5 { get; set; }
        public Nullable<decimal> year6item5 { get; set; }
        public Nullable<decimal> year7item5 { get; set; }
        public Nullable<decimal> year1item6 { get; set; }
        public Nullable<decimal> year2item6 { get; set; }
        public Nullable<decimal> year3item6 { get; set; }
        public Nullable<decimal> year4item6 { get; set; }
        public Nullable<decimal> year5item6 { get; set; }
        public Nullable<decimal> year6item6 { get; set; }
        public Nullable<decimal> year7item6 { get; set; }
        public Nullable<decimal> year8item1 { get; set; }
        public Nullable<decimal> year9item1 { get; set; }
        public Nullable<decimal> year10item1 { get; set; }
        public Nullable<decimal> year11item1 { get; set; }
        public Nullable<decimal> year12item1 { get; set; }
        public Nullable<decimal> year8item2 { get; set; }
        public Nullable<decimal> year9item2 { get; set; }
        public Nullable<decimal> year10item2 { get; set; }
        public Nullable<decimal> year11item2 { get; set; }
        public Nullable<decimal> year12item2 { get; set; }
        public Nullable<decimal> year8item3 { get; set; }
        public Nullable<decimal> year9item3 { get; set; }
        public Nullable<decimal> year10item3 { get; set; }
        public Nullable<decimal> year11item3 { get; set; }
        public Nullable<decimal> year12item3 { get; set; }
        public Nullable<decimal> year8item4 { get; set; }
        public Nullable<decimal> year9item4 { get; set; }
        public Nullable<decimal> year10item4 { get; set; }
        public Nullable<decimal> year11item4 { get; set; }
        public Nullable<decimal> year12item4 { get; set; }
        public Nullable<decimal> year8item5 { get; set; }
        public Nullable<decimal> year9item5 { get; set; }
        public Nullable<decimal> year10item5 { get; set; }
        public Nullable<decimal> year11item5 { get; set; }
        public Nullable<decimal> year12item5 { get; set; }
        public Nullable<decimal> year8item6 { get; set; }
        public Nullable<decimal> year9item6 { get; set; }
        public Nullable<decimal> year10item6 { get; set; }
        public Nullable<decimal> year11item6 { get; set; }
        public Nullable<decimal> year12item6 { get; set; }
        public Nullable<decimal> aiditem1 { get; set; }
        public Nullable<decimal> aiditem2 { get; set; }
        public Nullable<decimal> aiditem3 { get; set; }
        public Nullable<decimal> aiditem4 { get; set; }
        public Nullable<decimal> aiditem5 { get; set; }
        public Nullable<decimal> aiditem6 { get; set; }
        public Nullable<decimal> borritem1 { get; set; }
        public Nullable<decimal> borritem2 { get; set; }
        public Nullable<decimal> borritem3 { get; set; }
        public Nullable<decimal> borritem4 { get; set; }
        public Nullable<decimal> borritem5 { get; set; }
        public Nullable<decimal> borritem6 { get; set; }
    
        public virtual loan loan { get; set; }
    }
}
